version: '3.8'
services:
  nginx:
    image: nginx
    volumes:
      - .dockerconfig/nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/html
    ports:
      - 8001:80
  php:
    build: .dockerconfig/php
    volumes:
      - .:/var/www/html
    expose:
      - 9000
  composer:
    image: composer:2.0.13
    command: [ "composer", "update", "--ignore-platform-reqs"]
    volumes:
      - .:/app