version: '3.8'
services:
  nginx:
    image: nginx
    volumes:
      - .dockerconfig/nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/html
    ports:
      - 8000:80
  php:
    build: .dockerconfig/php
    volumes:
     # - .dockerconfig/php/php.ini:/user/local/etc/php/php.ini
      - .dockerconfig/php/ssl/openssl.cnf:/etc/ssl/openssl.cnf
      - .:/var/www/html
    expose:
      - 9000