<?php

namespace PlaygroundStudio\BlackBridge\PhpExtends;

class ThaiDateTime extends \DateTime
{

    private $dataThaiDay = [
        1 => "จันทร์",
        2 => "อังคาร",
        3 => "พุธ",
        4 => "พฤหัส",
        5 => "ศุกร์",
        6 => "เสาร์",
        7 => "อาทิตย์"
    ];

    private $dataThaiDayAbbr = [
        1 => "จ.",
        2 => "อ.",
        3 => "พ.",
        4 => "พฤ.",
        5 => "ศ",
        6 => "ส.",
        7 => "อา."
    ];

    private $dataThaiMonth = [
        1 => "มกราคม",
        2 => "กุมภาพันธ์",
        3 => "มีนาคม",
        4 => "เมษายน",
        5 => "พฤษภาคม",
        6 => "มิถุนายน",
        7 => "กรกฏาคม",
        8 => "สิงหาคม",
        9 => "กันยายน",
        10 => "ตุลาคม",
        11 => "พฤศจิกายน",
        12 => "ธันวาคม",
    ];

    // Abbreviation
    private $dataThaiMonthAbbr = [
        1 => "ม.ค.",
        2 => "ก.พ.",
        3 => "มี.ค.",
        4 => "เม.ย.",
        5 => "พ.ค.",
        6 => "มิ.ย.",
        7 => "ก.ค.",
        8 => "ส.ค.",
        9 => "ก.ย.",
        10 => "ต.ค.",
        11 => "พ.ย.",
        12 => "ธ.ค.",
    ];

    public function __construct($datetime = 'now', DateTimeZone $timezone = NULL)
    {
        parent::__construct($datetime, $timezone);
    }

    /**
     * ddd
     *
     * F-TH = เดือนไทย เต็มรูปแบบ
     * M-TH = เดือนไทย ตัวย่อ
     * Y-TH = ปี พ.ศ. 4 หลัก
     * y-TH = ปี พ.ศ. 2 หลัก
     * @param string $format
     *
     * @return string
     */
    public function format($format)
    {
        $N = parent::format('N');
        $day_full = $this->dataThaiDay[$N];
        $day_abbr = $this->dataThaiDayAbbr[$N];
        $format = str_replace('l-TH', $day_full, $format);
        $format = str_replace('D-TH', $day_abbr, $format);

        $n = parent::format('n');
        $month_full = $this->dataThaiMonth[$n];
        $month_abbr = $this->dataThaiMonthAbbr[$n];
        $format = str_replace('F-TH', $month_full, $format);
        $format = str_replace('M-TH', $month_abbr, $format);

        $yAD4 = parent::format('Y');
        $yBE4 = $yAD4 + 543;
        $yBE2 = $yBE4 % 100;
        $format = str_replace('Y-TH', $yBE4, $format);
        $format = str_replace('y-TH', $yBE2, $format);

        return parent::format($format); // TODO: Change the autogenerated stub
    }


}